//
export const ADD_APPOINTMENT_REQUEST = 'ADD_APPOINTMENT_REQUEST';
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_FAILURE = 'ADD_APPOINTMENT_FAILURE';

//
export const ALL_APPOINTMENTS_REQUEST = 'ALL_APPOINTMENTS_REQUEST';
export const ALL_APPOINTMENTS_SUCCESS = 'ALL_APPOINTMENTS_SUCCESS';
export const ALL_APPOINTMENTS_FAILURE = 'ALL_APPOINTMENTS_FAILURE';

//
export const ADMIN_ALL_APPOINTMENTS_REQUEST = 'ADMIN_ALL_APPOINTMENTS_REQUEST';
export const ADMIN_ALL_APPOINTMENTS_SUCCESS = 'ADMIN_ALL_APPOINTMENTS_SUCCESS';
export const ADMIN_ALL_APPOINTMENTS_FAILURE = 'ADMIN_ALL_APPOINTMENTS_FAILURE';

//
export const ADMIN_UPDATE_APPOINTMENT_REQUEST =
  'ADMIN_UPDATE_APPOINTMENT_REQUEST';
export const ADMIN_UPDATE_APPOINTMENT_SUCCESS =
  'ADMIN_UPDATE_APPOINTMENT_SUCCESS';
export const ADMIN_UPDATE_APPOINTMENT_RESET = 'ADMIN_UPDATE_APPOINTMENT_RESET';
export const ADMIN_UPDATE_APPOINTMENT_FAILURE =
  'ADMIN_UPDATE_APPOINTMENT_FAILURE';

//
export const ADMIN_DELETE_APPOINTMENT_REQUEST =
  'ADMIN_DELETE_APPOINTMENT_REQUEST';
export const ADMIN_DELETE_APPOINTMENT_SUCCESS =
  'ADMIN_DELETE_APPOINTMENT_SUCCESS';
export const ADMIN_DELETE_APPOINTMENT_RESET = 'ADMIN_DELETE_APPOINTMENT_RESET';
export const ADMIN_DELETE_APPOINTMENT_FAILURE =
  'ADMIN_DELETE_APPOINTMENT_FAILURE';

//
export const ADMIN_APPOINTMENT_DETAILS_REQUEST =
  'ADMIN_APPOINTMENT_DETAILS_REQUEST';
export const ADMIN_APPOINTMENT_DETAILS_SUCCESS =
  'ADMIN_APPOINTMENT_DETAILS_SUCCESS';
export const ADMIN_APPOINTMENT_DETAILS_FAILURE =
  'ADMIN_APPOINTMENT_DETAILS_FAILURE';

//
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
