// exporting signup constants
export const SIGNUP_AUTH_REQUEST = 'SIGNUP_AUTH_REQUEST';
export const SIGNUP_AUTH_SUCCESS = 'SIGNUP_AUTH_SUCCESS';
export const SIGNUP_AUTH_FAILURE = 'SIGNUP_AUTH_FAILURE';

// exporting signin constants
export const SIGNIN_AUTH_REQUEST = 'SIGNIN_AUTH_REQUEST';
export const SIGNIN_AUTH_SUCCESS = 'SIGNIN_AUTH_SUCCESS';
export const SIGNIN_AUTH_FAILURE = 'SIGNIN_AUTH_FAILURE';

// exporting google constants
export const GOOGLE_AUTH_REQUEST = 'GOOGLE_AUTH_REQUEST';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAILURE = 'GOOGLE_AUTH_FAILURE';

// exporting signout constants
export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';

// exporting forget password constants
export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'FORGET_PASSWORD_FAILURE';

// exporting reset password constants
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// exporting user load constants
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

// exporting update profile constants
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

// exporting update password constants
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

// exporting admin all users constants
export const ADMIN_ALL_USERS_REQUEST = 'ADMIN_ALL_USERS_REQUEST';
export const ADMIN_ALL_USERS_SUCCESS = 'ADMIN_ALL_USERS_SUCCESS';
export const ADMIN_ALL_USERS_FAILURE = 'ADMIN_ALL_USERS_FAILURE';

// exporting admin user details constants
export const ADMIN_USER_DETAILS_REQUEST = 'ADMIN_USER_DETAILS_REQUEST';
export const ADMIN_USER_DETAILS_SUCCESS = 'ADMIN_USER_DETAILS_SUCCESS';
export const ADMIN_USER_DETAILS_FAILURE = 'ADMIN_USER_DETAILS_FAILURE';

// exporting admin user role update constants
export const ADMIN_UPDATE_USER_ROLE_REQUEST = 'ADMIN_UPDATE_USER_ROLE_REQUEST';
export const ADMIN_UPDATE_USER_ROLE_SUCCESS = 'ADMIN_UPDATE_USER_ROLE_SUCCESS';
export const ADMIN_UPDATE_USER_ROLE_RESET = 'ADMIN_UPDATE_USER_ROLE_RESET';
export const ADMIN_UPDATE_USER_ROLE_FAILURE = 'ADMIN_UPDATE_USER_ROLE_FAILURE';

// exporting admin delete user constants
export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_RESET = 'ADMIN_DELETE_USER_RESET';
export const ADMIN_DELETE_USER_FAILURE = 'ADMIN_DELETE_USER_FAILURE';

// exporting auth and user error constant
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
