export const NEW_PRICE_REQUEST = 'NEW_PRICE_REQUEST';
export const NEW_PRICE_SUCCESS = 'NEW_PRICE_SUCCESS';
export const NEW_PRICE_RESET = 'NEW_PRICE_RESET';
export const NEW_PRICE_FAILURE = 'NEW_PRICE_FAILURE';

export const ADMIN_ALL_PRICES_REQUEST = 'ADMIN_ALL_PRICES_REQUEST';
export const ADMIN_ALL_PRICES_SUCCESS = 'ADMIN_ALL_PRICES_SUCCESS';
export const ADMIN_ALL_PRICES_FAILURE = 'ADMIN_ALL_PRICES_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
