export const ADMIN_NEW_PRICE_REQUEST = 'ADMIN_NEW_PRICE_REQUEST';
export const ADMIN_NEW_PRICE_SUCCESS = 'ADMIN_NEW_PRICE_SUCCESS';
export const ADMIN_NEW_PRICE_RESET = 'ADMIN_NEW_PRICE_RESET';
export const ADMIN_NEW_PRICE_FAILURE = 'ADMIN_NEW_PRICE_FAILURE';

export const ADMIN_ALL_PRICES_REQUEST = 'ADMIN_ALL_PRICES_REQUEST';
export const ADMIN_ALL_PRICES_SUCCESS = 'ADMIN_ALL_PRICES_SUCCESS';
export const ADMIN_ALL_PRICES_FAILURE = 'ADMIN_ALL_PRICES_FAILURE';

export const ADMIN_PRICE_DETAILS_REQUEST = 'ADMIN_PRICE_DETAILS_REQUEST';
export const ADMIN_PRICE_DETAILS_SUCCESS = 'ADMIN_PRICE_DETAILS_SUCCESS';
export const ADMIN_PRICE_DETAILS_FAILURE = 'ADMIN_PRICE_DETAILS_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
