export const NEW_SERVICE_REQUEST = 'NEW_SERVICE_REQUEST';
export const NEW_SERVICE_SUCCESS = 'NEW_SERVICE_SUCCESS';
export const NEW_SERVICE_RESET = 'NEW_SERVICE_RESET';
export const NEW_SERVICE_FAILURE = 'NEW_SERVICE_FAILURE';

export const ADMIN_ALL_SERVICES_REQUEST = 'ADMIN_ALL_SERVICES_REQUEST';
export const ADMIN_ALL_SERVICES_SUCCESS = 'ADMIN_ALL_SERVICES_SUCCESS';
export const ADMIN_ALL_SERVICES_FAILURE = 'ADMIN_ALL_SERVICES_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
