// exporting admin add service constants
export const ADMIN_NEW_SERVICE_REQUEST = 'ADMIN_NEW_SERVICE_REQUEST';
export const ADMIN_NEW_SERVICE_SUCCESS = 'ADMIN_NEW_SERVICE_SUCCESS';
export const ADMIN_NEW_SERVICE_RESET = 'ADMIN_NEW_SERVICE_RESET';
export const ADMIN_NEW_SERVICE_FAILURE = 'ADMIN_NEW_SERVICE_FAILURE';

// exporting all services constants
export const ALL_SERVICES_REQUEST = 'ALL_SERVICES_REQUEST';
export const ALL_SERVICES_SUCCESS = 'ALL_SERVICES_SUCCESS';
export const ALL_SERVICES_FAILURE = 'ALL_SERVICES_FAILURE';

// exporting service details constants
export const SERVICE_DETAILS_REQUEST = 'SERVICE_DETAILS_REQUEST';
export const SERVICE_DETAILS_SUCCESS = 'SERVICE_DETAILS_SUCCESS';
export const SERVICE_DETAILS_FAILURE = 'SERVICE_DETAILS_FAILURE';

// exporting admin all services constants
export const ADMIN_ALL_SERVICES_REQUEST = 'ADMIN_ALL_SERVICES_REQUEST';
export const ADMIN_ALL_SERVICES_SUCCESS = 'ADMIN_ALL_SERVICES_SUCCESS';
export const ADMIN_ALL_SERVICES_FAILURE = 'ADMIN_ALL_SERVICES_FAILURE';

// exporting admin service details constants
export const ADMIN_SERVICE_DETAILS_REQUEST = 'ADMIN_SERVICE_DETAILS_REQUEST';
export const ADMIN_SERVICE_DETAILS_SUCCESS = 'ADMIN_SERVICE_DETAILS_SUCCESS';
export const ADMIN_SERVICE_DETAILS_FAILURE = 'ADMIN_SERVICE_DETAILS_FAILURE';

// exporting admin update service details constants
export const ADMIN_UPDATE_SERVICE_DETAILS_REQUEST =
  'ADMIN_UPDATE_SERVICE_DETAILS_REQUEST';
export const ADMIN_UPDATE_SERVICE_DETAILS_SUCCESS =
  'ADMIN_UPDATE_SERVICE_DETAILS_SUCCESS';
export const ADMIN_UPDATE_SERVICE_DETAILS_RESET =
  'ADMIN_UPDATE_SERVICE_DETAILS_RESET';
export const ADMIN_UPDATE_SERVICE_DETAILS_FAILURE =
  'ADMIN_UPDATE_SERVICE_DETAILS_FAILURE';

// exporting admin delete service details constants
export const ADMIN_DELETE_SERVICE_DETAILS_REQUEST =
  'ADMIN_DELETE_SERVICE_DETAILS_REQUEST';
export const ADMIN_DELETE_SERVICE_DETAILS_SUCCESS =
  'ADMIN_DELETE_SERVICE_DETAILS_SUCCESS';
export const ADMIN_DELETE_SERVICE_DETAILS_RESET =
  'ADMIN_DELETE_SERVICE_DETAILS_RESET';
export const ADMIN_DELETE_SERVICE_DETAILS_FAILURE =
  'ADMIN_DELETE_SERVICE_DETAILS_FAILURE';

// exporting service error constant
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
