export const ADMIN_NEW_SERVICE_REQUEST = 'ADMIN_NEW_SERVICE_REQUEST';
export const ADMIN_NEW_SERVICE_SUCCESS = 'ADMIN_NEW_SERVICE_SUCCESS';
export const ADMIN_NEW_SERVICE_RESET = 'ADMIN_NEW_SERVICE_RESET';
export const ADMIN_NEW_SERVICE_FAILURE = 'ADMIN_NEW_SERVICE_FAILURE';

export const ADMIN_ALL_SERVICES_REQUEST = 'ADMIN_ALL_SERVICES_REQUEST';
export const ADMIN_ALL_SERVICES_SUCCESS = 'ADMIN_ALL_SERVICES_SUCCESS';
export const ADMIN_ALL_SERVICES_FAILURE = 'ADMIN_ALL_SERVICES_FAILURE';

export const ADMIN_SERVICE_DETAILS_REQUEST = 'ADMIN_SERVICE_DETAILS_REQUEST';
export const ADMIN_SERVICE_DETAILS_SUCCESS = 'ADMIN_SERVICE_DETAILS_SUCCESS';
export const ADMIN_SERVICE_DETAILS_FAILURE = 'ADMIN_SERVICE_DETAILS_FAILURE';

export const ADMIN_UPDATE_SERVICE_DETAILS_REQUEST =
  'ADMIN_UPDATE_SERVICE_DETAILS_REQUEST';
export const ADMIN_UPDATE_SERVICE_DETAILS_SUCCESS =
  'ADMIN_UPDATE_SERVICE_DETAILS_SUCCESS';
export const ADMIN_UPDATE_SERVICE_DETAILS_RESET =
  'ADMIN_UPDATE_SERVICE_DETAILS_RESET';
export const ADMIN_UPDATE_SERVICE_DETAILS_FAILURE =
  'ADMIN_UPDATE_SERVICE_DETAILS_FAILURE';

export const ADMIN_DELETE_SERVICE_DETAILS_REQUEST =
  'ADMIN_DELETE_SERVICE_DETAILS_REQUEST';
export const ADMIN_DELETE_SERVICE_DETAILS_SUCCESS =
  'ADMIN_DELETE_SERVICE_DETAILS_SUCCESS';
export const ADMIN_DELETE_SERVICE_DETAILS_RESET =
  'ADMIN_DELETE_SERVICE_DETAILS_RESET';
export const ADMIN_DELETE_SERVICE_DETAILS_FAILURE =
  'ADMIN_DELETE_SERVICE_DETAILS_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
