// exporting add testimonial constants
export const ADD_TESTIMONIAL_REQUEST = 'ADD_TESTIMONIAL_REQUEST';
export const ADD_TESTIMONIAL_SUCCESS = 'ADD_TESTIMONIAL_SUCCESS';
export const ADD_TESTIMONIAL_FAILURE = 'ADD_TESTIMONIAL_FAILURE';
export const ADD_TESTIMONIAL_RESET = 'ADD_TESTIMONIAL_RESET';

// exporting all testimonials constants
export const ALL_TESTIMONIALS_REQUEST = 'ALL_TESTIMONIALS_REQUEST';
export const ALL_TESTIMONIALS_SUCCESS = 'ALL_TESTIMONIALS_SUCCESS';
export const ALL_TESTIMONIALS_FAILURE = 'ALL_TESTIMONIALS_FAILURE';

// exporting admin delete testimonial constants
export const ADMIN_DELETE_TESTIMONIAL_REQUEST =
  'ADMIN_DELETE_TESTIMONIAL_REQUEST';
export const ADMIN_DELETE_TESTIMONIAL_SUCCESS =
  'ADMIN_DELETE_TESTIMONIAL_SUCCESS';
export const ADMIN_DELETE_TESTIMONIAL_RESET = 'ADMIN_DELETE_TESTIMONIAL_RESET';
export const ADMIN_DELETE_TESTIMONIAL_FAILURE =
  'ADMIN_DELETE_TESTIMONIAL_FAILURE';

// exporting testimonial error constant
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
